name: Deploy to EC2

on:
  push:
    branches:
      - main  # Or whatever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to EC2!"

            echo "🚀 Updating frontend..."
            cd ~/Desktop/foreverFrontend
            git pull
            npm install
            npm run build

            echo "🔄 Reloading NGINX..."
            sudo systemctl reload nginx
            
            echo "✅ Deploy done!"

